import type { Event, EventWithStats, ListingWithSeller } from '@/lib/types/database';

export const DEMO_MODE = false;

const demoEvents: Event[] = [
  {
    id: 'demo-1',
    home_team: 'מכבי תל אביב',
    away_team: 'הפועל באר שבע',
    date: '2026-04-18',
    time: '20:00',
    stadium: 'אצטדיון בלומפילד',
    city: 'תל אביב',
    status: 'upcoming',
  },
  {
    id: 'demo-2',
    home_team: 'מכבי חיפה',
    away_team: 'בית"ר ירושלים',
    date: '2026-04-19',
    time: '19:30',
    stadium: 'אצטדיון סמי עופר',
    city: 'חיפה',
    status: 'upcoming',
  },
  {
    id: 'demo-3',
    home_team: 'הפועל תל אביב',
    away_team: 'מכבי נתניה',
    date: '2026-04-20',
    time: '20:15',
    stadium: 'אצטדיון בלומפילד',
    city: 'תל אביב',
    status: 'upcoming',
  },
  {
    id: 'demo-4',
    home_team: 'הפועל חיפה',
    away_team: 'בני סחנין',
    date: '2026-04-25',
    time: '19:00',
    stadium: 'אצטדיון סמי עופר',
    city: 'חיפה',
    status: 'upcoming',
  },
  {
    id: 'demo-5',
    home_team: 'בית"ר ירושלים',
    away_team: 'מכבי תל אביב',
    date: '2026-04-26',
    time: '20:30',
    stadium: 'אצטדיון טדי',
    city: 'ירושלים',
    status: 'upcoming',
  },
  {
    id: 'demo-6',
    home_team: 'מ.ס. אשדוד',
    away_team: 'הפועל ירושלים',
    date: '2026-05-02',
    time: '19:00',
    stadium: 'אצטדיון י"א אשדוד',
    city: 'אשדוד',
    status: 'upcoming',
  },
];

const DEMO_STATS = [
  { listing_count: 5, min_price: 120 },
  { listing_count: 3, min_price: 90 },
  { listing_count: 8, min_price: 80 },
  { listing_count: 2, min_price: 150 },
  { listing_count: 12, min_price: 200 },
  { listing_count: 1, min_price: 70 },
] as const;

export const demoEventsWithStats: EventWithStats[] = demoEvents.map((event, i) => ({
  ...event,
  listing_count: DEMO_STATS[i]?.listing_count ?? 0,
  min_price: DEMO_STATS[i]?.min_price ?? null,
}));

export function getDemoEvent(id: string): Event | undefined {
  return demoEvents.find((e) => e.id === id);
}

export const demoListings: Record<string, ListingWithSeller[]> = {
  'demo-1': [
    {
      id: 'listing-1a',
      event_id: 'demo-1',
      seller_id: 'seller-1',
      price: 120,
      section: 'יציע מזרחי',
      row_number: '12',
      seat_number: '8',
      quantity: 1,
      notes: null,
      status: 'active',
      profiles: { name: 'דוד כהן', phone: '050-1234567', whatsapp: '0501234567' },
    },
    {
      id: 'listing-1b',
      event_id: 'demo-1',
      seller_id: 'seller-2',
      price: 150,
      section: 'יציע מערבי',
      row_number: '5',
      seat_number: '14',
      quantity: 1,
      notes: null,
      status: 'active',
      profiles: { name: 'יוסי לוי', phone: '052-9876543', whatsapp: '0529876543' },
    },
    {
      id: 'listing-1c',
      event_id: 'demo-1',
      seller_id: 'seller-3',
      price: 200,
      section: 'יציע כסף',
      row_number: '2',
      seat_number: '22',
      quantity: 1,
      notes: 'מקום מרכזי עם נוף מצוין',
      status: 'active',
      profiles: { name: 'משה ישראלי', phone: '054-5551234', whatsapp: '0545551234' },
    },
  ],
  'demo-2': [
    {
      id: 'listing-2a',
      event_id: 'demo-2',
      seller_id: 'seller-4',
      price: 90,
      section: 'יציע צפוני',
      row_number: '18',
      seat_number: '3',
      quantity: 1,
      notes: null,
      status: 'active',
      profiles: { name: 'אבי שמעוני', phone: '053-1112222', whatsapp: '0531112222' },
    },
    {
      id: 'listing-2b',
      event_id: 'demo-2',
      seller_id: 'seller-5',
      price: 130,
      section: 'יציע מזרחי',
      row_number: '7',
      seat_number: '19',
      quantity: 1,
      notes: null,
      status: 'active',
      profiles: { name: 'רון חיים', phone: '050-3334444', whatsapp: '0503334444' },
    },
  ],
  'demo-3': [
    {
      id: 'listing-3a',
      event_id: 'demo-3',
      seller_id: 'seller-6',
      price: 80,
      section: 'יציע דרומי',
      row_number: '20',
      seat_number: '11',
      quantity: 1,
      notes: null,
      status: 'active',
      profiles: { name: 'נועם גולן', phone: '058-7778888', whatsapp: '0587778888' },
    },
  ],
  'demo-4': [
    {
      id: 'listing-4a',
      event_id: 'demo-4',
      seller_id: 'seller-7',
      price: 150,
      section: 'יציע מערבי',
      row_number: '3',
      seat_number: '6',
      quantity: 1,
      notes: null,
      status: 'active',
      profiles: { name: 'עומר פרץ', phone: '052-6665555', whatsapp: '0526665555' },
    },
  ],
  'demo-5': [
    {
      id: 'listing-5a',
      event_id: 'demo-5',
      seller_id: 'seller-8',
      price: 200,
      section: 'יציע מזרחי',
      row_number: '1',
      seat_number: '15',
      quantity: 1,
      notes: 'שורה ראשונה!',
      status: 'active',
      profiles: { name: 'תומר אלון', phone: '050-9998877', whatsapp: '0509998877' },
    },
    {
      id: 'listing-5b',
      event_id: 'demo-5',
      seller_id: 'seller-9',
      price: 250,
      section: 'יציע כסף',
      row_number: '4',
      seat_number: '10',
      quantity: 1,
      notes: null,
      status: 'active',
      profiles: { name: 'גיל מזרחי', phone: '054-1122334', whatsapp: '0541122334' },
    },
  ],
  'demo-6': [
    {
      id: 'listing-6a',
      event_id: 'demo-6',
      seller_id: 'seller-10',
      price: 70,
      section: 'יציע צפוני',
      row_number: '25',
      seat_number: '4',
      quantity: 1,
      notes: null,
      status: 'active',
      profiles: { name: 'אלי דהן', phone: '053-4455667', whatsapp: '0534455667' },
    },
  ],
};
